# 🐼 100 Pandas Practical Questions
> **Instructions:** Try to solve each question on your own. Use the hints only if you are stuck.  
> Progress: Basic → Intermediate → Advanced  
> Recommended pace: 10–15 questions per day

---

## 🔹 Section 1: Basics & Series (Q1–Q20)

---

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

---

In [2]:
import pandas as pd

data = ([10,20,30,40,50])
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

---

In [3]:
data = ([11,22,33,44,55])
s =  dict[pd.Series(data)]
print(s)

dict[0    11
1    22
2    33
3    44
4    55
dtype: int64]

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

---

In [4]:
data = ([56,89,23,52,51,46,26,13])

c = pd.Series(data)
print(c)

c[3]

c[2:5]

0    56
1    89
2    23
3    52
4    51
5    46
6    26
7    13
dtype: int64

2    23
3    52
4    51
dtype: int64

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

---

In [6]:
s1 = pd.Series([20,3,45,56,89,75])
s2=pd.Series([56,23,42,65,10,32])


print(s1 + s2 )
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)
print(s1 // s2)
print(s1 % s2)
print(s1 ** s2)

0     76
1     26
2     87
3    121
4     99
5    107
dtype: int64
0   -36
1   -20
2     3
3    -9
4    79
5    43
dtype: int64
0    1120
1      69
2    1890
3    3640
4     890
5    2400
dtype: int64
0    0.357143
1    0.130435
2    1.071429
3    0.861538
4    8.900000
5    2.343750
dtype: float64
0    0
1    0
2    1
3    0
4    8
5    2
dtype: int64
0    20
1     3
2     3
3    56
4     9
5    11
dtype: int64
0                      0
1            94143178827
2   -2262772019283983735
3                      0
4   -5711768217452919631
5   -6428525364353835647
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

---

In [7]:
s1 = pd.Series([20,3,45,56,89,75])
print(s1)

print(s1.mean())
print(s1.min())
print(s1.max())
print(s1.sum())
print(s1.median())
print(s1.std())

0    20
1     3
2    45
3    56
4    89
5    75
dtype: int64
48.0
3
89
288
50.5
32.5330601081423

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

---

In [8]:
s1 = pd.Series([20,3,45,56,89,75])

s1[s1 > 50 ]

3    56
4    89
5    75
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

---

In [9]:
s1 = pd.Series([20,3,45,56,89,75])
print(s1)
print(s1.replace(45,95))

0    20
1     3
2    45
3    56
4    89
5    75
dtype: int64
0    20
1     3
2    95
3    56
4    89
5    75
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

---

In [10]:
s1 = pd.Series([20,3,45,56,89,75])
print(s1.dtype)
print(s1.astype('Int32'))
print(s1.astype(float))
print(s1.astype('category'))

int64
0    20
1     3
2    45
3    56
4    89
5    75
dtype: Int32
0    20.0
1     3.0
2    45.0
3    56.0
4    89.0
5    75.0
dtype: float64
0    20
1     3
2    45
3    56
4    89
5    75
dtype: category
Categories (6, int64): [3, 20, 45, 56, 75, 89]

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

---

In [11]:
import numpy as np

s1 = pd.Series([20,3, np.nan, 45,np.nan,56,89,75, np.nan, np.nan])
s1.isnull()
s1.isnull().sum()

np.int64(4)

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

---

In [12]:
s1 = pd.Series([20,3, np.nan, 45,np.nan,56,89,75, np.nan, np.nan])
#print(s1)

print(s1.fillna(25))
print(s1.fillna(s1.mean()))
print(s1.ffill())
print(s1.bfill())

0    20.0
1     3.0
2    25.0
3    45.0
4    25.0
5    56.0
6    89.0
7    75.0
8    25.0
9    25.0
dtype: float64
0    20.0
1     3.0
2    48.0
3    45.0
4    48.0
5    56.0
6    89.0
7    75.0
8    48.0
9    48.0
dtype: float64
0    20.0
1     3.0
2     3.0
3    45.0
4    45.0
5    56.0
6    89.0
7    75.0
8    75.0
9    75.0
dtype: float64
0    20.0
1     3.0
2    45.0
3    45.0
4    56.0
5    56.0
6    89.0
7    75.0
8     NaN
9     NaN
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

---

In [13]:
data = [
    [101,'sai', 95 ],
    [102, 'ramesh', 85],
    [103, 'ganesh', 45]
]

s1 = pd.DataFrame(data, columns=['Id', 'Name', 'Age'])
print(s1)

    Id    Name  Age
0  101     sai   95
1  102  ramesh   85
2  103  ganesh   45

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

---

In [14]:
data = {
    'Id' : [101,102,103],
    'Name': ['sai', 'ram', 'ganesh'],
    'age' : [25,56,23]
}
s1 = pd.DataFrame(data)
print(s1)

    Id    Name  age
0  101     sai   25
1  102     ram   56
2  103  ganesh   23

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

---

In [106]:
data = [
    {'id' : 101, 'name':'sai', 'age' : 25},
    {'id': 104,  'age': 26},
    {'id': 103, 'name' : 'ganesh'}

]

s1 = pd.DataFrame(data)
print(s1)
print(s1.shape)
print(s1.ndim)

    id    name   age
0  101     sai  25.0
1  104     NaN  26.0
2  103  ganesh   NaN
(3, 3)
2

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

---

In [15]:
data = {
    'Id' : [101,102,103],
    'Name' : ['sai', 'sumit', 'krishna'],
    'age' : [25,26,27]
}
print(data, type(data))
s = pd.DataFrame(data)
print(s)
print(s.dtypes)
print(s.shape)
print(s.columns)
print(s.info())
print(s.describe())

{'Id': [101, 102, 103], 'Name': ['sai', 'sumit', 'krishna'], 'age': [25, 26, 27]} <class 'dict'>
    Id     Name  age
0  101      sai   25
1  102    sumit   26
2  103  krishna   27
Id       int64
Name    object
age      int64
dtype: object
(3, 3)
Index(['Id', 'Name', 'age'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      3 non-null      int64
 1   Name    3 non-null      object
 2   age     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None
          Id   age
count    3.0   3.0
mean   102.0  26.0
std      1.0   1.0
min    101.0  25.0
25%    101.5  25.5
50%    102.0  26.0
75%    102.5  26.5
max    103.0  27.0

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

---

In [16]:
data =  {
    'id' : ['pawar', 'saiprasad', 'kiran'],
    'number' : [98,78,85],
    'age' : [101,102,103]

}
s1 = pd.DataFrame(data)
print(s1)

s1["id"]
s1["age"]
s1["number"]

          id  number  age
0      pawar      98  101
1  saiprasad      78  102
2      kiran      85  103

0    98
1    78
2    85
Name: number, dtype: int64

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

---

In [17]:
data = pd.DataFrame({
    'id':[101,102,103],
    'age': [55,65,75],
    'name' :['sai', 'pawar', 'vivek']
})
print(data)

data[['id', 'name']]

    id  age   name
0  101   55    sai
1  102   65  pawar
2  103   75  vivek

    id   name
0  101    sai
1  102  pawar
2  103  vivek

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

---

In [18]:
data["bonus"] = 25
print(data)

    id  age   name  bonus
0  101   55    sai     25
1  102   65  pawar     25
2  103   75  vivek     25

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

---

In [19]:
data["balance"] = pd.Series([5000,10000,150000])
print(data)

    id  age   name  bonus  balance
0  101   55    sai     25     5000
1  102   65  pawar     25    10000
2  103   75  vivek     25   150000

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

---

In [20]:
data = data.rename(columns={"balance":"amount"})
print(data)

    id  age   name  bonus  amount
0  101   55    sai     25    5000
1  102   65  pawar     25   10000
2  103   75  vivek     25  150000

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

---

In [21]:
data = data.rename(columns={"id" : "Unique_id", "age" : "maturity", "name": "nickname"})
print(data)

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000
2        103        75    vivek     25  150000

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

---

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

---

In [22]:
data.loc[0],

data.loc[0:1]

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

---

In [23]:
data.iloc[0]
data.iloc[0:1]  #exclusive
data.iloc[0:2]

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

---

In [24]:
print(data)

data.loc[0, 'nickname']
data.iloc[0,2]

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000
2        103        75    vivek     25  150000

'sai'

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

---

In [25]:
data.loc[[0,1], ['nickname', 'amount']]
data.iloc[[0,1], [0,2]]

   Unique_id nickname
0        101      sai
1        102    pawar

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

---

In [28]:
print(data)
data.loc[data['maturity'] >60, ['maturity','bonus', 'amount'] ]   #Needs understanding

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000
2        103        75    vivek     25  150000

   maturity  bonus  amount
1        65     25   10000
2        75     25  150000

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

---

In [29]:
data.iloc[0:2]
data.loc[0:2]

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000
2        103        75    vivek     25  150000

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

---

In [30]:
data.loc[:, "maturity":"amount"]

   maturity nickname  bonus  amount
0        55      sai     25    5000
1        65    pawar     25   10000
2        75    vivek     25  150000

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

---

In [31]:
data.loc[:, "maturity":"nickname"]
data.iloc[:, 1:4]

   maturity nickname  bonus
0        55      sai     25
1        65    pawar     25
2        75    vivek     25

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

---

In [32]:
data.loc[0:1,"maturity" : "amount"]

print(data)

data['city'] = "banaras"
print(data)

new_rows = pd.DataFrame({
    "Unique_id" : [104,105,106],
    "maturity" : [85,95,105],
    "nickname" : ["nikhil", "krishna", "vaibhav"],
    "bonus" : [35,45,55],
    "amount" : [65000,4500,5556]
})
print(new_rows)

data = pd.concat([data, new_rows], ignore_index = True)
print(data)

data.iloc[0:5,[0,2,4]]

   Unique_id  maturity nickname  bonus  amount
0        101        55      sai     25    5000
1        102        65    pawar     25   10000
2        103        75    vivek     25  150000
   Unique_id  maturity nickname  bonus  amount     city
0        101        55      sai     25    5000  banaras
1        102        65    pawar     25   10000  banaras
2        103        75    vivek     25  150000  banaras
   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556
   Unique_id  maturity nickname  bonus  amount     city
0        101        55      sai     25    5000  banaras
1        102        65    pawar     25   10000  banaras
2        103        75    vivek     25  150000  banaras
3        104        85   nikhil     35   65000      NaN
4        105        95  krishna     45    4500      NaN
5        106       105  vaibhav     55    5556      NaN

   Unique_id nickname  amount
0        101      sai    5000
1        102    pawar   10000
2        103    vivek  150000
3        104   nikhil   65000
4        105  krishna    4500

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

---

In [33]:
new_rows.set_index("Unique_id").inplace = True
print(new_rows)                                   #not understanded

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

---

In [34]:
new_rows.set_index(["maturity", "nickname", "bonus"])
print(new_rows)

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

---

In [ ]:
new_rows.reset_index()
print(new_rows)               #not understanded

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

---

In [35]:
new_rows.reset_index()
print(new_rows)

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

---

In [36]:
new_rows.reset_index(drop=False)
print(new_rows)

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

---

In [37]:
new_rows.reset_index(drop=True)
print(new_rows)

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

---

In [ ]:

new_rows.loc[]

   Unique_id  maturity nickname  bonus  amount
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

---

In [194]:
new_rows.iloc[0:3]

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500
2        106       105  vaibhav     55    5556

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

---

In [41]:
new_rows.head(2)

   Unique_id  maturity nickname  bonus  amount
0        104        85   nikhil     35   65000
1        105        95  krishna     45    4500

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

---

In [42]:
data.tail(3)

   Unique_id  maturity nickname  bonus  amount city
3        104        85   nikhil     35   65000  NaN
4        105        95  krishna     45    4500  NaN
5        106       105  vaibhav     55    5556  NaN

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

---

In [210]:
data.sample(3)

s= pd.DataFrame([10,30,50,45,70])
print(s)
s.sample(2)
s.sample(frac=0.2, random_state=20)

    0
0  10
1  30
2  50
3  45
4  70

    0
1  30

## 🔹 Section 3: Data Cleaning (Q41–Q60)

---

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

---

In [43]:
data1 = pd.DataFrame([2,45,12,23,56,89,np.nan,np.nan, 74, 56, np.nan,np.nan])
print(data1)
print(data1.isnull())
print(data1.isnull().sum())
print(data1.isnull().any())

       0
0    2.0
1   45.0
2   12.0
3   23.0
4   56.0
5   89.0
6    NaN
7    NaN
8   74.0
9   56.0
10   NaN
11   NaN
        0
0   False
1   False
2   False
3   False
4   False
5   False
6    True
7    True
8   False
9   False
10   True
11   True
0    4
dtype: int64
0    True
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

---

In [52]:


data = data.dropna(subset=['city'])
print(data)  #not understand

   Unique_id  maturity nickname  bonus  amount     city
0        101        55      sai     25    5000  banaras
1        102        65    pawar     25   10000  banaras
2        103        75    vivek     25  150000  banaras

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

---

In [ ]:
result = pd.DataFrame({
    "id" : [102,103,104,105,np.nan,107,108],
    "name" :['sai','ram', 'ganesh', 'sumit', 'soma', 'nikhil', 'krishna'],
    "salary" : [4500,5500,6500,7500,8500,np.nan,3500],
    "age" : [56,78,45,np.nan,36,56,np.nan],
    "bonus":[10,np.nan,30,40,50,60, np.nan]
})

result=result.fillna(0)
result['age'] = result['age'].fillna(25)
print(result)                                   #not understanded




#data = data['age'].fillna(2)
#data=data['bonus'].fillna(20)
#print(data)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    0.0
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   0.0   40.0
4    0.0     soma  8500.0  36.0   50.0
5  107.0   nikhil     0.0  56.0   60.0
6  108.0  krishna  3500.0   0.0    0.0

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

---

In [76]:
data = pd.DataFrame({
    "id" : [102,103,104,105,np.nan,107,108],
    "name" :['sai','ram', 'ganesh', 'sumit', 'soma', 'nikhil', 'krishna'],
    "salary" : [4500,5500,6500,7500,8500,np.nan,3500],
    "age" : [56,78,45,np.nan,36,56,np.nan],
    "bonus":[10,np.nan,30,40,50,60, np.nan]
})
print(data)

data['bonus'] = data['bonus'].fillna(data['bonus'].mean())
print(data)

data['age'] = data['age'].fillna(data['age'].median())
print(data)

data['id'] = data['id'].fillna(data['id'].median())
print(data)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN
      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0   38.0
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN   38.0
      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0   38.0
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0  56.0   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0  56.0   38.0
      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0   38.0
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0  56.0   40.0
4  104.5     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0  56.0   38.0

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

---

In [85]:
print(data)
data.ffill()
data.bfill()

[[      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0   38.0
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0  56.0   40.0
4  104.5     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0  56.0   38.0,   Married
0     yes
1      no
2     yes
3     yes
4      no
5     yes],   Married
0     yes
1      no
2     yes
3     yes
4      no
5     yes]

AttributeError: 'list' object has no attribute 'ffill'

### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

---

In [ ]:
data = pd.DataFrame({
    "id" : [102,103,104,105,np.nan,107,108],
    "name" :['sai','ram', 'ganesh', 'sumit', 'soma', 'nikhil', 'krishna'],
    "salary" : [4500,5500,6500,7500,8500,np.nan,3500],
    "age" : [56,78,45,np.nan,36,56,np.nan],
    "bonus":[10,np.nan,30,40,50,60, np.nan]
})

print(data)
new_rows = pd.DataFrame({
    'Married' : ['yes', 'no', 'yes','yes', 'no', 'yes']
})
print(new_rows)

result = pd.concat([data, new_rows])
print("result", result)

result = result.drop(['Married'], axis=1)
print(result)

result['Married'] = ({
    'Married':['yes', 'no' ,'yes', 'yes', 'no', 'no', 'no','no','yes','yes']
})
print(result)

result['Married'] = result['Married'].fillna('yes')
print(result)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN
  Married
0     yes
1      no
2     yes
3     yes
4      no
5     yes
result       id     name  salary   age  bonus Married
0  102.0      sai  4500.0  56.0   10.0     NaN
1  103.0      ram  5500.0  78.0    NaN     NaN
2  104.0   ganesh  6500.0  45.0   30.0     NaN
3  105.0    sumit  7500.0   NaN   40.0     NaN
4    NaN     soma  8500.0  36.0   50.0     NaN
5  107.0   nikhil     NaN  56.0   60.0     NaN
6  108.0  krishna  3500.0   NaN    NaN     NaN
0    NaN      NaN     NaN   NaN    NaN     yes
1    NaN      NaN     NaN   NaN    NaN      no
2    NaN      NaN     NaN   NaN    NaN     yes
3    NaN      NaN     NaN   NaN    NaN     yes
4    NaN      NaN     NaN   NaN    NaN      no
5    NaN      NaN     NaN   NaN    NaN     yes
      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN
0    NaN      NaN     NaN   NaN    NaN
1    NaN      NaN     NaN   NaN    NaN
2    NaN      NaN     NaN   NaN    NaN
3    NaN      NaN     NaN   NaN    NaN
4    NaN      NaN     NaN   NaN    NaN
5    NaN      NaN     NaN   NaN    NaN
      id     name  salary   age  bonus Married
0  102.0      sai  4500.0  56.0   10.0     NaN
1  103.0      ram  5500.0  78.0    NaN     NaN
2  104.0   ganesh  6500.0  45.0   30.0     NaN
3  105.0    sumit  7500.0   NaN   40.0     NaN
4    NaN     soma  8500.0  36.0   50.0     NaN
5  107.0   nikhil     NaN  56.0   60.0     NaN
6  108.0  krishna  3500.0   NaN    NaN     NaN
0    NaN      NaN     NaN   NaN    NaN     NaN
1    NaN      NaN     NaN   NaN    NaN     NaN
2    NaN      NaN     NaN   NaN    NaN     NaN
3    NaN      NaN     NaN   NaN    NaN     NaN
4    NaN      NaN     NaN   NaN    NaN     NaN
5    NaN      NaN     NaN   NaN    NaN     NaN
      id     name  salary   age  bonus Married
0  102.0      sai  4500.0  56.0   10.0     yes
1  103.0      ram  5500.0  78.0    NaN     yes
2  104.0   ganesh  6500.0  45.0   30.0     yes
3  105.0    sumit  7500.0   NaN   40.0     yes
4    NaN     soma  8500.0  36.0   50.0     yes
5  107.0   nikhil     NaN  56.0   60.0     yes
6  108.0  krishna  3500.0   NaN    NaN     yes
0    NaN      NaN     NaN   NaN    NaN     yes
1    NaN      NaN     NaN   NaN    NaN     yes
2    NaN      NaN     NaN   NaN    NaN     yes
3    NaN      NaN     NaN   NaN    NaN     yes
4    NaN      NaN     NaN   NaN    NaN     yes
5    NaN      NaN     NaN   NaN    NaN     yes

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

---

In [96]:
data['name'].str.lower()
data['name'].str.upper()

data['name'].str.title()

0        Sai
1        Ram
2     Ganesh
3      Sumit
4       Soma
5     Nikhil
6    Krishna
Name: name, dtype: object

### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

---

In [97]:
data['name'].str.strip()
data['name'].str.lstrip()
data['name'].str.rstrip()

0        sai
1        ram
2     ganesh
3      sumit
4       soma
5     nikhil
6    krishna
Name: name, dtype: object

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

---

In [100]:
data["name"].str.replace('name', 'surname').regex = True

print(data)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

---

In [101]:
data["name"].str[:3]

data['name'].str.split("@").str[1]
print(data)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

---

In [102]:
data[data.duplicated()]

Empty DataFrame
Columns: [id, name, salary, age, bonus]
Index: []

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

---

In [103]:
data.drop_duplicates()

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

---

In [110]:
data.rename(index={102:101})
data.rename(index={0:1})
data.rename(index={1:2})
data.rename(index={2:3})

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
3  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

---

In [141]:
data = pd.DataFrame({
    "id" : [102,103,104,105,np.nan,107,108],
    "name" :['sai','ram', 'ganesh', 'sumit', 'soma', 'nikhil', 'krishna'],
    "salary" : [4500,5500,6500,7500,8500,np.nan,3500],
    "age" : [56,78,45,np.nan,36,56,np.nan],
    "bonus":[10,np.nan,30,40,50,60, np.nan]
})

print(data)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN

### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

---

In [161]:
#print(data)
#print(data.replace('sai','rahul'))

result = data.replace('ram', 'vilas')
#print("result:", result)

result = result.replace('ganesh', 'ramesh')
#print("result2 :",result)

result = result.replace({'rahul', 'sai'})
#print("columns specific:", result)

result =result.replace({
    'salary': {4500 : 9875}
})
#print("nested", result)

result = result.replace({
    'age':{56 : 25}
})

print(result)

      id     name  salary   age  bonus
0  102.0      sai  9875.0  25.0   10.0
1  103.0    vilas  5500.0  78.0    NaN
2  104.0   ramesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  25.0   60.0
6  108.0  krishna  3500.0   NaN    NaN

C:\Users\saipr\AppData\Local\Temp\ipykernel_6168\2213584989.py:10: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  result = result.replace({'rahul', 'sai'})

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

---

In [166]:
print(data)

Q1 = data['age'].quantile(0.25)
print('Q1 :',Q1)

Q3 = data['age'].quantile(0.75)
print('Q3 :',Q3)

IQR = Q3 - Q1
print('IQR : ', IQR)

below = Q1 - 1.5*IQR
above = Q3 + 1.5*IQR

print('below :',below)
print('above :', above)

      id     name  salary   age  bonus
0  102.0      sai  4500.0  56.0   10.0
1  103.0      ram  5500.0  78.0    NaN
2  104.0   ganesh  6500.0  45.0   30.0
3  105.0    sumit  7500.0   NaN   40.0
4    NaN     soma  8500.0  36.0   50.0
5  107.0   nikhil     NaN  56.0   60.0
6  108.0  krishna  3500.0   NaN    NaN
Q1 : 45.0
Q3 : 56.0
IQR :  11.0
below : 28.5
above : 72.5

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

---

In [169]:
data['bonus'].clip(lower = 10, upper=50)

0    10.0
1     NaN
2    30.0
3    40.0
4    50.0
5    50.0
6     NaN
Name: bonus, dtype: float64

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

---

In [22]:
import pandas as pd


data = {
    "id": [101, 102, 103, 104, 105, 106, 107, 108],
    "name": ["John", "Alice", "Bob", None, "David", "Emma", "Chris", "Sophia"],
    "age": [25, 30, None, 35, 40, 28, None, 32],
    "salary": [50000, 60000, 55000, None, 80000, 65000, 70000, None],
    "bonus": [5000, None, 5500, 7000, 8000, None, 6500, 7200],
    "married": ["No", "Yes", "No", "Yes", None, "No", "Yes", None],
    "department": ["IT", "HR", "Finance", "IT", "Sales", None, "HR", "Finance"],
    "experience": [2, 5, 3, None, 10, 4, 6, 7]
}

data = pd.DataFrame(data)
#print(data)

data.columns=(data.columns.str.upper())
#print(data)

data.columns = (data.columns.str.replace('EXPERIENCE','EXP'))
#print(data)

data.columns = (data.columns.str.replace('DEPARTMENT', 'Dept'))
#print(data)

data.columns = (data.columns.str.strip())
print(data)

    ID    NAME   AGE   SALARY   BONUS MARRIED     Dept   EXP
0  101    John  25.0  50000.0  5000.0      No       IT   2.0
1  102   Alice  30.0  60000.0     NaN     Yes       HR   5.0
2  103     Bob   NaN  55000.0  5500.0      No  Finance   3.0
3  104    None  35.0      NaN  7000.0     Yes       IT   NaN
4  105   David  40.0  80000.0  8000.0    None    Sales  10.0
5  106    Emma  28.0  65000.0     NaN      No     None   4.0
6  107   Chris   NaN  70000.0  6500.0     Yes       HR   6.0
7  108  Sophia  32.0      NaN  7200.0    None  Finance   7.0

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

---

In [73]:
#print(data)


result = {
    "id": [101, 102, "103A", 104, None, 106],
    "name": ["John", "Alice", None, "Emma", 123, "David"],
    "age": [25, "30", None, 35, "Unknown", 40],
    "salary": [50000, "60000", None, 75000.50, "N/A", 80000],
    "bonus": [5000, None, "5500", 7000, "Not Given", 8000],
    "married": ["Yes", "No", True, False, None, "Yes"],
    "department": ["IT", "HR", 101, None, "Sales", "Finance"]
}

result = pd.DataFrame(result)
#print(result)

#result['columns'] = (result.columns.str.upper())

result.columns = (result.columns.str.upper())
#print(result)



result["BONUS"] = pd.to_numeric(result["BONUS"], errors='coerce')
#print(result)

result['AGE'] = pd.to_numeric(result['AGE'], errors='coerce')

#result['ID', 'SALARY'] = pd.to_numeric(result['ID', 'SALARY'], errors='coerce')  #wrong way

result[['ID','SALARY']] = result[['ID', 'SALARY']].apply(
    pd.to_numeric, errors = 'coerce'
)


result['MARRIED'] = result['MARRIED'].astype('category')

result['SALARY'] = result['SALARY'].mean()

mean_bonus = result['BONUS'].mean()
print('mean_bonus',mean_bonus)
result['BONUS'] = result['BONUS'].fillna(mean_bonus).mean()

mean_age = result['AGE'].mean()
print('mean_age', mean_age)

result['AGE'] = result['AGE'].fillna(mean_age)

print(result)
#print(result.dtypes)

mean_bonus 6375.0
mean_age 32.5
      ID   NAME   AGE     SALARY   BONUS MARRIED DEPARTMENT
0  101.0   John  25.0  66250.125  6375.0     Yes         IT
1  102.0  Alice  30.0  66250.125  6375.0      No         HR
2    NaN   None  32.5  66250.125  6375.0    True        101
3  104.0   Emma  35.0  66250.125  6375.0   False       None
4    NaN    123  32.5  66250.125  6375.0     NaN      Sales
5  106.0  David  40.0  66250.125  6375.0     Yes    Finance

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

In [75]:


data = {
    "text": [
        "John@123",
        "#Alice!",
        "$50000",
        "Hello!!!",
        "Data_Science",
        "Python#3.12",
        "Machine-Learning",
        "AI & ML",
        "100%",
        "(Pandas)",
        "[NumPy]",
        "{Scikit-Learn}",
        "John_Doe@Gmail.com",
        "Hello, World!",
        "C++",
        "SQL*Server",
        "###Test###",
        "@@@Python@@@",
        "   Data Analyst   ",
        None
    ]
}

special = pd.DataFrame(data)

print(special)

special['text'] = special['text'].str.replace(r"[^a-zA-Z0-9]","" , regex = True)

print(special)

                  text
0             John@123
1              #Alice!
2               $50000
3             Hello!!!
4         Data_Science
5          Python#3.12
6     Machine-Learning
7              AI & ML
8                 100%
9             (Pandas)
10             [NumPy]
11      {Scikit-Learn}
12  John_Doe@Gmail.com
13       Hello, World!
14                 C++
15          SQL*Server
16          ###Test###
17        @@@Python@@@
18     Data Analyst
19                None
               text
0           John123
1             Alice
2             50000
3             Hello
4       DataScience
5         Python312
6   MachineLearning
7              AIML
8               100
9            Pandas
10            NumPy
11      ScikitLearn
12  JohnDoeGmailcom
13       HelloWorld
14                C
15        SQLServer
16             Test
17           Python
18      DataAnalyst
19             None

## 🔹 Section 4: Data Manipulation (Q61–Q80)

---

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

---

In [174]:


result = {
    "id": [101, 102, "103A", 104, None, 106],
    "name": ["John", "Alice", None, "Emma", 123, "David"],
    "age": [25, "30", None, 35, "Unknown", 40],
    "salary": [50000, "60000", None, 75000.50, "N/A", 80000],
    "bonus": [5000, None, "5500", 7000, "Not Given", 8000],
    "married": ["Yes", "No", True, False, None, "Yes"],
    "department": ["IT", "HR", 101, None, "Sales", "Finance"]
}

In [3]:
#print(result)
#print(data)

import pandas as pd
'''

result2 = result[(result['age'] > 30) & (result['age'] < 40)]
#print(result2)

result3 = result[(result['salary'] >60000 ) & (result['salary'] == 75000)]   #Empty Dataframe
print(result3)
'''





result = {
    "id": [101, 102, "103A", 104, None, 106],
    "name": ["John", "Alice", None, "Emma", 123, "David"],
    "age": [25, "30", None, 35, "Unknown", 40],
    "salary": [50000, "60000", None, 75000.50, "N/A", 80000],
    "bonus": [5000, None, "5500", 7000, "Not Given", 8000],
    "married": ["Yes", "No", True, False, None, "Yes"],
    "department": ["IT", "HR", 101, None, "Sales", "Finance"]
}

result = pd.DataFrame(result)
#print(result)

result['age'] = pd.to_numeric(result['age'], errors='coerce',)

result[['id', 'salary', 'bonus' ]] = result[['id','salary','bonus']].apply(
                                  pd.to_numeric, errors='coerce'
)

result['name'] = result['name'].astype('category')


age_mean = result['age'].mean()
salary_mean=  result['salary'].mean()
bonus_mean = result['bonus'].mean()

#print('age_mean', age_mean)
#print('salary_mean', salary_mean)
#print('bonus_mean',bonus_mean) 

result['age']  = result['age'].fillna(age_mean)
result['salary'] = result['salary'].fillna(salary_mean)
result['bonus'] = result['bonus'].fillna(bonus_mean)

result['name'] = result['name'].astype('str')
result['married'] = result['married'].astype('category')

result['name'] = result['name'].replace('123', 'ramesh')
result['name']  = result['name'].replace('nan', 'sai')

id_median = result['id'].median()

#print(id_median)

result['id'] = result['id'].fillna(id_median)

#print(result)
#print(result.dtypes)

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

---

In [4]:
#print(result)


rows = result[(result['age'] > 35) | (result['salary'] == 75000.500)]
print(rows)

      id   name   age   salary   bonus married department
3  104.0   Emma  35.0  75000.5  7000.0   False       None
5  106.0  David  40.0  80000.0  8000.0     Yes    Finance

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

---

In [5]:


result = result[~(result['salary'] == 75000.500)]

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

---

In [6]:
#print(result)

result = result.sort_values('salary', ascending=False)
result = result.sort_values('bonus', ascending=False)
print(result)
#print(result1)

print(type(result))

      id    name   age     salary   bonus married department
5  106.0   David  40.0  80000.000  8000.0     Yes    Finance
4  103.0  ramesh  32.5  66250.125  6375.0     NaN      Sales
1  102.0   Alice  30.0  60000.000  6375.0      No         HR
2  103.0     sai  32.5  66250.125  5500.0    True        101
0  101.0    John  25.0  50000.000  5000.0     Yes         IT
<class 'pandas.core.frame.DataFrame'>

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

---

In [7]:
#print(result)
result = result.sort_index(ascending=False,axis=1)
print(result)

      salary    name married     id department   bonus   age
5  80000.000   David     Yes  106.0    Finance  8000.0  40.0
4  66250.125  ramesh     NaN  103.0      Sales  6375.0  32.5
1  60000.000   Alice      No  102.0         HR  6375.0  30.0
2  66250.125     sai    True  103.0        101  5500.0  32.5
0  50000.000    John     Yes  101.0         IT  5000.0  25.0

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

---

In [8]:
print(result)
result = result.sort_index(ascending=True, axis=0)

      salary    name married     id department   bonus   age
5  80000.000   David     Yes  106.0    Finance  8000.0  40.0
4  66250.125  ramesh     NaN  103.0      Sales  6375.0  32.5
1  60000.000   Alice      No  102.0         HR  6375.0  30.0
2  66250.125     sai    True  103.0        101  5500.0  32.5
0  50000.000    John     Yes  101.0         IT  5000.0  25.0

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

---

In [9]:
#result = result.drop(columns=['id'])
print(result)

result1 = result.drop(0,axis=0)
#print(result1)

result2 = result1.drop('married', axis=1)
print(result2)

print(result)

      salary    name married     id department   bonus   age
0  50000.000    John     Yes  101.0         IT  5000.0  25.0
1  60000.000   Alice      No  102.0         HR  6375.0  30.0
2  66250.125     sai    True  103.0        101  5500.0  32.5
4  66250.125  ramesh     NaN  103.0      Sales  6375.0  32.5
5  80000.000   David     Yes  106.0    Finance  8000.0  40.0
      salary    name     id department   bonus   age
1  60000.000   Alice  102.0         HR  6375.0  30.0
2  66250.125     sai  103.0        101  5500.0  32.5
4  66250.125  ramesh  103.0      Sales  6375.0  32.5
5  80000.000   David  106.0    Finance  8000.0  40.0
      salary    name married     id department   bonus   age
0  50000.000    John     Yes  101.0         IT  5000.0  25.0
1  60000.000   Alice      No  102.0         HR  6375.0  30.0
2  66250.125     sai    True  103.0        101  5500.0  32.5
4  66250.125  ramesh     NaN  103.0      Sales  6375.0  32.5
5  80000.000   David     Yes  106.0    Finance  8000.0  40.0

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

---

In [11]:
#print(result)

result1 = result.drop(index=[0,3])
print(result1)

KeyError: '[3] not found in axis'

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

---

In [12]:
#print(result)

result['married'] = result['married'].map({'yes':1,  'no':0})
print(result)

      salary    name  married     id department   bonus   age
0  50000.000    John      NaN  101.0         IT  5000.0  25.0
1  60000.000   Alice      NaN  102.0         HR  6375.0  30.0
2  66250.125     sai      NaN  103.0        101  5500.0  32.5
4  66250.125  ramesh      NaN  103.0      Sales  6375.0  32.5
5  80000.000   David      NaN  106.0    Finance  8000.0  40.0

### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

---

In [13]:
#print(result)

print(result['bonus'].apply(lambda x:x*2))

result['bonus']=result['bonus'].apply(lambda x:x*2)



print(result)

0    10000.0
1    12750.0
2    11000.0
4    12750.0
5    16000.0
Name: bonus, dtype: float64
      salary    name  married     id department    bonus   age
0  50000.000    John      NaN  101.0         IT  10000.0  25.0
1  60000.000   Alice      NaN  102.0         HR  12750.0  30.0
2  66250.125     sai      NaN  103.0        101  11000.0  32.5
4  66250.125  ramesh      NaN  103.0      Sales  12750.0  32.5
5  80000.000   David      NaN  106.0    Finance  16000.0  40.0

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

---

In [14]:

print(result)

result1 = result.map(lambda x: x*2)
print(result1)

      salary    name  married     id department    bonus   age
0  50000.000    John      NaN  101.0         IT  10000.0  25.0
1  60000.000   Alice      NaN  102.0         HR  12750.0  30.0
2  66250.125     sai      NaN  103.0        101  11000.0  32.5
4  66250.125  ramesh      NaN  103.0      Sales  12750.0  32.5
5  80000.000   David      NaN  106.0    Finance  16000.0  40.0
      salary          name  married     id      department    bonus   age
0  100000.00      JohnJohn      NaN  202.0            ITIT  20000.0  50.0
1  120000.00    AliceAlice      NaN  204.0            HRHR  25500.0  60.0
2  132500.25        saisai      NaN  206.0             202  22000.0  65.0
4  132500.25  rameshramesh      NaN  206.0      SalesSales  25500.0  65.0
5  160000.00    DavidDavid      NaN  212.0  FinanceFinance  32000.0  80.0

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

---

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

---

In [15]:
#print(result)

normalize = (result['salary'] - result['salary'].min()) / (result['salary'].max() - result['salary'].min())

print("normalize", normalize)

normalize 0    0.000000
1    0.333333
2    0.541671
4    0.541671
5    1.000000
Name: salary, dtype: float64

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

---

In [16]:
z_score = (result['salary'] - result['salary'].mean()) / result['salary'].std()
print("z_score", z_score)
print(type(z_score))

z_score 0   -1.327996
1   -0.412140
2    0.160282
4    0.160282
5    1.419573
Name: salary, dtype: float64
<class 'pandas.core.series.Series'>

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

---

In [17]:
rank = result['salary'].rank(ascending=False, method = 'dense')
print("rank", rank)

rank 0    4.0
1    3.0
2    2.0
4    2.0
5    1.0
Name: salary, dtype: float64

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

---

In [18]:
#print(result)

bins =pd.cut(result['age'], bins=[0,25,50,75,100], labels=['Low', 'Mid', 'High', 'Top'])
print(bins)

bins2 = pd.cut(result['age'], bins=[0,25,50,75,100])
print("bins2", bins2)
'''
bins3 = pd.cut(result['age'], labels=['low','med','high','top'])   #throws error
print("bins3", bins3)  '''

0    Low
1    Mid
2    Mid
4    Mid
5    Mid
Name: age, dtype: category
Categories (4, object): ['Low' < 'Mid' < 'High' < 'Top']
bins2 0     (0, 25]
1    (25, 50]
2    (25, 50]
4    (25, 50]
5    (25, 50]
Name: age, dtype: category
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

'\nbins3 = pd.cut(result[\'age\'], labels=[\'low\',\'med\',\'high\',\'top\'])   #throws error\nprint("bins3", bins3)  '

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

---

In [24]:
bins1 = pd.cut(result['age'], bins=[25,56,66,89,41])
print(bins1)


bins = pd.qcut(result['salary'], q=4,labels=['Q1','Q2','Q3','Q4'])
print(bins)

ValueError: bins must increase monotonically.

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

---

In [25]:
unique  = result['age'].nunique()
print("unique", unique)

freq = result['age'].value_counts()
print('freq', freq)

unique 4
freq age
32.5    2
25.0    1
30.0    1
40.0    1
Name: count, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

---

In [29]:
#print(result)
replace = result.replace({
    "age": {
        25 : 39, 30:52
    }
})
print(replace)

listed = result.replace([32.5,32.5],65)
print("listed", listed)

      salary    name  married     id department    bonus   age
0  50000.000    John      NaN  101.0         IT  10000.0  39.0
1  60000.000   Alice      NaN  102.0         HR  12750.0  52.0
2  66250.125     sai      NaN  103.0        101  11000.0  32.5
4  66250.125  ramesh      NaN  103.0      Sales  12750.0  32.5
5  80000.000   David      NaN  106.0    Finance  16000.0  40.0
listed       salary    name  married     id department    bonus   age
0  50000.000    John      NaN  101.0         IT  10000.0  25.0
1  60000.000   Alice      NaN  102.0         HR  12750.0  30.0
2  66250.125     sai      NaN  103.0        101  11000.0  65.0
4  66250.125  ramesh      NaN  103.0      Sales  12750.0  65.0
5  80000.000   David      NaN  106.0    Finance  16000.0  40.0

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

---

In [38]:
#print(result)

import numpy as np

np.random.seed(12)


result['married']  = np.random.choice(
    ['Yes', 'No'],
    size = len(result)
)

print(result)
result['married'] = (result['married'] > 'Yes').astype(int)

#flag = result['married']

      salary    name married     id department    bonus   age
0  50000.000    John      No  101.0         IT  10000.0  25.0
1  60000.000   Alice      No  102.0         HR  12750.0  30.0
2  66250.125     sai     Yes  103.0        101  11000.0  32.5
4  66250.125  ramesh      No  103.0      Sales  12750.0  32.5
5  80000.000   David      No  106.0    Finance  16000.0  40.0

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

---

### Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

---

In [40]:
for idx, row in result.iterrows():
    print(idx ,'-->',row)

0 --> salary        50000.0
name             John
married             0
id              101.0
department         IT
bonus         10000.0
age              25.0
Name: 0, dtype: object
1 --> salary        60000.0
name            Alice
married             0
id              102.0
department         HR
bonus         12750.0
age              30.0
Name: 1, dtype: object
2 --> salary        66250.125
name                sai
married               0
id                103.0
department          101
bonus           11000.0
age                32.5
Name: 2, dtype: object
4 --> salary        66250.125
name             ramesh
married               0
id                103.0
department        Sales
bonus           12750.0
age                32.5
Name: 4, dtype: object
5 --> salary        80000.0
name            David
married             0
id              106.0
department    Finance
bonus         16000.0
age              40.0
Name: 5, dtype: object

### Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

---

In [42]:
for row in result.itertuples():
    row.salary
    print("row", row)

row Pandas(Index=0, salary=50000.0, name='John', married=0, id=101.0, department='IT', bonus=10000.0, age=25.0)
row Pandas(Index=1, salary=60000.0, name='Alice', married=0, id=102.0, department='HR', bonus=12750.0, age=30.0)
row Pandas(Index=2, salary=66250.125, name='sai', married=0, id=103.0, department=101, bonus=11000.0, age=32.5)
row Pandas(Index=4, salary=66250.125, name='ramesh', married=0, id=103.0, department='Sales', bonus=12750.0, age=32.5)
row Pandas(Index=5, salary=80000.0, name='David', married=0, id=106.0, department='Finance', bonus=16000.0, age=40.0)

### Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

---

In [49]:
for col in result.columns:
    result.items()
    print(result)

      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0
      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0
      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0
      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0
      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0
      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0
      salary    name  married     id department    bonus   age
0  50000.000    John        0  101.0         IT  10000.0  25.0
1  60000.000   Alice        0  102.0         HR  12750.0  30.0
2  66250.125     sai        0  103.0        101  11000.0  32.5
4  66250.125  ramesh        0  103.0      Sales  12750.0  32.5
5  80000.000   David        0  106.0    Finance  16000.0  40.0

### Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

---

In [25]:
import pandas as pd
import numpy as np


frame = pd.DataFrame({
    'id' : [1,2,3,4,5,6],
    'name' : ['sai', 'ram', 'krishna' , 'shubham', 'ramesh', 'vilas'],
    'scores' : [70,81,36,25,66,22],
    'age' : [56,89,52,54,75,13],
    'salary' : [8500,9500,7500,6500,5500,4500]
})

print(frame)


frame['age'] = frame['scores'] * 2+1
print(frame)

   id     name  scores  age  salary
0   1      sai      70   56    8500
1   2      ram      81   89    9500
2   3  krishna      36   52    7500
3   4  shubham      25   54    6500
4   5   ramesh      66   75    5500
5   6    vilas      22   13    4500
   id     name  scores  age  salary
0   1      sai      70  141    8500
1   2      ram      81  163    9500
2   3  krishna      36   73    7500
3   4  shubham      25   51    6500
4   5   ramesh      66  133    5500
5   6    vilas      22   45    4500

### Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

---

In [96]:
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.head())


survived = df.groupby('sex')['survived'].mean()
#print(survived)

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

---

In [97]:
sum = df.groupby('age')['fare'].sum()
print('age by sum',sum)

age by sum age
0.42       8.5167
0.67      14.5000
0.75      38.5166
0.83      47.7500
0.92     151.5500
           ...
70.00     81.5000
70.50      7.7500
71.00     84.1584
74.00      7.7750
80.00     30.0000
Name: fare, Length: 88, dtype: float64

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

---

In [98]:
#print(df)

multiple = df.groupby('class')['fare'].agg([
    'mean', 'sum', 'min', 'max']
)

print(multiple)

             mean         sum  min       max
class
First   84.154687  18177.4125  0.0  512.3292
Second  20.662183   3801.8417  0.0   73.5000
Third   13.675550   6714.6951  0.0   69.5500

C:\Users\saipr\AppData\Local\Temp\ipykernel_12404\2353777991.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  multiple = df.groupby('class')['fare'].agg([

### Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

---

In [99]:
multiple = df.groupby(['sex', 'class']) ['fare'].mean()
print(multiple)

sex     class
female  First     106.125798
        Second     21.970121
        Third      16.118810
male    First      67.226127
        Second     19.741782
        Third      12.661633
Name: fare, dtype: float64

C:\Users\saipr\AppData\Local\Temp\ipykernel_12404\862384924.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  multiple = df.groupby(['sex', 'class']) ['fare'].mean()

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

---

In [100]:
#print(df)
survived = df.groupby('age').filter(lambda x : x['fare'].mean() > 20000)
print(survived)

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

### Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

---

In [101]:

transform = df.groupby('age')['fare'].transform('mean', 'max', 'sum')
print(transform)

0      25.504781
1      62.751509
2      19.086806
3      89.312500
4      89.312500
         ...
886    30.361339
887    27.869496
888          NaN
889    19.086806
890    24.323378
Name: fare, Length: 891, dtype: float64

### Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

---

In [102]:
custom = df.groupby('survived')['age'].agg(lambda x : x.max() - x.min())
#print(df.dtypes)
print(custom)

survived
0    73.00
1    79.58
Name: age, dtype: float64

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="scores", index='age', columns="salary", aggfunc="mean")`.

---

In [103]:
#print(df)
pivot = pd.pivot_table(df, values = 'fare', index='class', columns='sex', aggfunc='mean')
print(pivot)

sex         female       male
class
First   106.125798  67.226127
Second   21.970121  19.741782
Third    16.118810  12.661633

C:\Users\saipr\AppData\Local\Temp\ipykernel_12404\2639128651.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = pd.pivot_table(df, values = 'fare', index='class', columns='sex', aggfunc='mean')

### Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

---

In [104]:
#print(df)
import pandas as pd
import seaborn as sns

pivot = pd.pivot_table(df, values = 'age', index='sex', columns='survived', aggfunc=['mean', 'max'] )
print(pivot)

               mean              max
survived          0          1     0     1
sex
female    25.046875  28.847716  57.0  63.0
male      31.618056  27.276022  74.0  80.0

### Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

---

In [105]:
#print(df)
#print(df.isnull().sum())

#print(df.dtypes)

deck = df['deck'] = df['deck'].fillna('A')
print(deck)

0      A
1      C
2      A
3      C
4      A
      ..
886    A
887    B
888    A
889    C
890    A
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

### Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

---

In [106]:
margins = pd.pivot_table(df, values ='fare', index='sex', aggfunc='mean', margins=True, margins_name = 'Total')
print(margins)

             fare
sex
female  44.479818
male    25.523893
Total   32.204208

### Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

---

In [ ]:
#print(df.dtypes)
'''
pivot = pd.pivot_table(df, 
                       values='age',
                       index = 'sex',
                       columns= 'survived',
                       aggfunc= 'mean'
                       )

print(pivot) 
 survived          0          1
sex                           
female    25.046875  28.847716
male      31.618056  27.276022  '''

'''
pivot2 = pd.pivot_table(df,
                        values = 'age',
                        index = ['sex', 'class'],
                        columns = 'survived',
                        aggfunc= 'mean')

print(pivot2)

survived               0          1
sex    class                       
female First   25.666667  34.939024
       Second  36.000000  28.080882
       Third   23.818182  19.329787
male   First   44.581967  36.248000
       Second  33.369048  16.022000
       Third   27.255814  22.274211
'''

'''
pivot3 = pd.pivot_table(
    df, 
    values = 'age',
    index = 'sex',
    columns = ['survived', 'class'],
    aggfunc= 'mean'
)

print(pivot3)

survived          0                                1                      
class         First     Second      Third      First     Second      Third
sex                                                                       
female    25.666667  36.000000  23.818182  34.939024  28.080882  19.329787
male      44.581967  33.369048  27.255814  36.248000  16.022000  22.274211
'''

survived          0                                1
class         First     Second      Third      First     Second      Third
sex
female    25.666667  36.000000  23.818182  34.939024  28.080882  19.329787
male      44.581967  33.369048  27.255814  36.248000  16.022000  22.274211

C:\Users\saipr\AppData\Local\Temp\ipykernel_12404\2140278043.py:35: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot3 = pd.pivot_table(

### Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

---

In [129]:
#print(df)

data = pd.DataFrame({
    'id' : [1,2,3,4,5,6],
    'age' : [25,35,45,65,88,55],
    'name' : ['sai', 'pawar', 'yogesh', 'ramesh', 'nikhil', 'krushna']
})
print(data)

pivot = pd.pivot(data, index ='name', columns = 'id', values ='age')
print(pivot)

   id  age     name
0   1   25      sai
1   2   35    pawar
2   3   45   yogesh
3   4   65   ramesh
4   5   88   nikhil
5   6   55  krushna
id          1     2     3     4     5     6
name
krushna   NaN   NaN   NaN   NaN   NaN  55.0
nikhil    NaN   NaN   NaN   NaN  88.0   NaN
pawar     NaN  35.0   NaN   NaN   NaN   NaN
ramesh    NaN   NaN   NaN  65.0   NaN   NaN
sai      25.0   NaN   NaN   NaN   NaN   NaN
yogesh    NaN   NaN  45.0   NaN   NaN   NaN

### Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

---

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

---

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:  
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

---

*📌 Remember: Try solving without hints first. Look at hints only when genuinely stuck.*